name: Secret Scan

on:
  push:
    branches: [master]
  pull_request:

permissions:
  contents: read

jobs:
  leash-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Scan for leaked secrets
        uses: FasterApiWeb/leash-secrets/action@leash-secrets-v1.2.1
        with:
          scan-mode: all
          fail-on: critical
          exclude: build/**,node_modules/**
